### ISSUE TITLE
can not exit backoffice translation because of "wait for team approval" popup.

### ISSUE THREAD

**Issue by backamblock** [PrestaShop/ps_livetranslation#4]
please make this usable even when i am not an "approved translation team member" because i can never exit the loop of popups. glad that i made a backup just before.

regards

**Comment by MalikKrak** [comment]
Same here - when at admin backend I see only the pop-up, I can't do anything else.
So I deleted cookies and login again, but then I see this:

![capture](https://user-images.githubusercontent.com/46598938/51078280-0b891100-16b3-11e9-8d4e-68303e048dce.PNG)

**Comment by backamblock** [comment]
just recover your backup and use that plugin never again.. after i was approved and translated a few things, my already done translations got overwritten from remote and all my time translating with this **** module was lost...

**Comment by Progi1984** [comment]
Bug confirmed and fixed in the PR #9. ;)

**Comment by Progi1984** [comment]
Fixed by #9.
